### ISSUE TITLE
installation issue by cmake

### ISSUE THREAD

**Issue by wangzhezhe** [doyubkim/fluid-engine-dev#193] opened 2018-10-07 20:52 UTC
Hello, I use mac 10.13.4, Python 2.7.10, cmake version 3.12.3, and I get following errors when I run `mkdir build && cd build && cmake .. && make` , could you help me to solve this error? Thanks!

```
[ 83%] Built target sandbox
[ 84%] Building CXX object src/python/CMakeFiles/pyjet.dir/collocated_vector_grid.cpp.o
/Users/Hessen/cworkspace/fluid-engine-dev/src/python/collocated_vector_grid.cpp:116:49: error: no viable conversion from 'py::function' to
      'const std::function<void (size_t, size_t)>'
                 instance.forEachDataPointIndex(func);
                                                ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1448:5: note: candidate constructor not viable: no known
      conversion from 'py::function' to 'nullptr_t' for 1st argument
    function(nullptr_t) _NOEXCEPT : __f_(0) {}
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1449:5: note: candidate constructor not viable: no known
      conversion from 'py::function' to 'const std::__1::function<void (unsigned long, unsigned long)> &' for 1st argument
    function(const function&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1450:5: note: candidate constructor not viable: no known
      conversion from 'py::function' to 'std::__1::function<void (unsigned long, unsigned long)> &&' for 1st argument
    function(function&&) _NOEXCEPT;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1454:41: note: candidate template ignored: disabled by
      'enable_if' [with _Fp = pybind11::function]
                                        __callable<_Fp>::value &&
                                        ^
/Users/Hessen/cworkspace/fluid-engine-dev/include/jet/collocated_vector_grid2.h:66:52: note: passing argument to parameter 'func' here
        const std::function<void(size_t, size_t)>& func) const;
                                                   ^
/Users/Hessen/cworkspace/fluid-engine-dev/src/python/collocated_vector_grid.cpp:260:49: error: no viable conversion from 'py::function' to
      'const std::function<void (size_t, size_t, size_t)>'
                 instance.forEachDataPointIndex(func);
                                                ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1448:5: note: candidate constructor not viable: no known
      conversion from 'py::function' to 'nullptr_t' for 1st argument
    function(nullptr_t) _NOEXCEPT : __f_(0) {}
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1449:5: note: candidate constructor not viable: no known
      conversion from 'py::function' to 'const std::__1::function<void (unsigned long, unsigned long, unsigned long)> &' for 1st argument
    function(const function&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1450:5: note: candidate constructor not viable: no known
      conversion from 'py::function' to 'std::__1::function<void (unsigned long, unsigned long, unsigned long)> &&' for 1st argument
    function(function&&) _NOEXCEPT;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1454:41: note: candidate template ignored: disabled by
      'enable_if' [with _Fp = pybind11::function]
                                        __callable<_Fp>::value &&
                                        ^
/Users/Hessen/cworkspace/fluid-engine-dev/include/jet/collocated_vector_grid3.h:66:60: note: passing argument to parameter 'func' here
        const std::function<void(size_t, size_t, size_t)>& func) const;
                                                           ^
2 errors generated.
make[2]: *** [src/python/CMakeFiles/pyjet.dir/collocated_vector_grid.cpp.o] Error 1
make[1]: *** [src/python/CMakeFiles/pyjet.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by doyubkim** [comment] 2018-10-08 00:16
Thanks for reporting the issue. I will take a look!

**Comment by doyubkim** [comment] 2018-10-08 05:56
I don’t have exactly the same configuration on my hand, but when I build the latest code with macOS 10.14 + Python 2.7.15 (via Miniconda), I was not able to reproduce this. 

Can you provide more information including which commit ID are you at? Also, can you also try cloning (with recursive flag) a fresh copy of the code and try rebuilding it again?

**Comment by wangzhezhe** [comment] 2018-10-09 00:32
Thanks, It works for me after updating the Xcode. BTW, what visualization tool is used to show the data in different time step for this project? I tested several examples in  ./bin , some of them output .obj data and some output  .xyz data.

**Comment by doyubkim** [comment] 2018-10-09 01:33
Great to hear it got fixed by updating Xcode! Both obj and xyz files can be visualized with other open source packages such as MeshLab. For manual_tests output, you can use render scripts under scripts folder.

**Closed** 2018-10-09 01:33 UTC
